
default:
	pdflatex Day1.tex
	pdflatex Day1.tex
	pdflatex Day2.tex
	pdflatex Day2.tex
	rm *.aux *.log *.nav *.out *.snm *.toc *.vrb *~

day1:
	pdflatex Day1.tex
	pdflatex Day1.tex
	rm *.aux *.log *.nav *.out *.snm *.toc *.vrb *~

day2:
	pdflatex Day2.tex
	pdflatex Day2.tex
	rm *.aux *.log *.nav *.out *.snm *.toc *.vrb *~

clean:
	rm *.aux *.log *.nav *.out *.snm *.toc *.vrb

